// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	startManualSession: (serverAddr: string) => typedError<null, string>(__TAURI_INVOKE("start_manual_session", { serverAddr })),
	startAutoSession: (useWindivert: boolean, portMin: number, portMax: number) => typedError<null, string>(__TAURI_INVOKE("start_auto_session", { useWindivert, portMin, portMax })),
	stopSession: () => typedError<null, string>(__TAURI_INVOKE("stop_session")),
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	getSupportedVersions: () => __TAURI_INVOKE<string[]>("get_supported_versions"),
	getLocalIpAddr: () => __TAURI_INVOKE<string>("get_local_ip_addr"),
	checkUpdates: () => typedError<{
	tag: string,
	link: string,
} | null, string>(__TAURI_INVOKE("check_updates")),
	downloadAndInstallUpdate: (url: string) => typedError<null, string>(__TAURI_INVOKE("download_and_install_update", { url })),
	openUrl: (url: string) => __TAURI_INVOKE<void>("open_url", { url }),
	getPlatform: () => __TAURI_INVOKE<string>("get_platform"),
	setPanicMode: (value: boolean) => typedError<null, string>(__TAURI_INVOKE("set_panic_mode", { value })),
	getPendingChangelogs: () => typedError<ChangelogEntry[], string>(__TAURI_INVOKE("get_pending_changelogs")),
	acknowledgeChangelog: () => typedError<null, string>(__TAURI_INVOKE("acknowledge_changelog")),
	getManualWarningAcknowledged: () => __TAURI_INVOKE<boolean>("get_manual_warning_acknowledged"),
	acknowledgeManualWarning: () => typedError<null, string>(__TAURI_INVOKE("acknowledge_manual_warning")),
};

/** Events */
export const events = {
	clientStatusEvent: makeEvent<ClientStatusEvent>("client-status-event"),
	nickNameEvent: makeEvent<NickNameEvent>("nick-name-event"),
	proxyLogEvent: makeEvent<ProxyLogEvent>("proxy-log-event"),
	serverAddrEvent: makeEvent<ServerAddrEvent>("server-addr-event"),
	sessionEndedEvent: makeEvent<SessionEndedEvent>("session-ended-event"),
	sessionStartedEvent: makeEvent<SessionStartedEvent>("session-started-event"),
	updateProgressEvent: makeEvent<UpdateProgressEvent>("update-progress-event"),
};

/* Types */
export type ChangelogEntry = {
	version: string,
	html: string,
};

export type ClientStatusEvent = {
	which: WhichClient,
	online: boolean,
};

export type LogLevel = "Info" | "Success" | "Warn" | "Error";

export type NickNameEvent = string;

export type ProxyLogEvent = {
	level: LogLevel,
	message: string,
};

export type ServerAddrEvent = string;

export type SessionEndedEvent = null;

export type SessionStartedEvent = null;

export type UpdateInfo = {
	tag: string,
	link: string,
};

export type UpdateProgressEvent = {
	downloaded: number,
	total: number,
};

export type WhichClient = "Primary" | "Secondary";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

